### ISSUE TITLE
Scipy.signal dependencies

### ISSUE THREAD

**Issue by Emillio007** [Ulm-IQO/qudi-core#99]
### Version

Release v1.5.0

### What is affected by the bug?

Windows 10, QUDI 1.5.0, specifically when using qudi-iqo-modules. Running clean python 3.10.4 installation.
GUI's with scipy signal windows are affected due to deprecated dependency in math.py. Directory listed in comments. 

### When does the bug occur?

upon loading GUI's with signal windows functions.

### How do we replicate the issue?

Load any configuration in iqo-modules

### Expected behavior

No error-messages.

### Relevant log output

```shell
2024-06-12 13:31:29 info qudi.Qudi Starting qudi...
2024-06-12 13:31:29 info qudi.Qudi Applying configuration from "C:/Users/emilh/qudi/config/default.cfg"...
2024-06-12 13:31:29 info qudi.Qudi Qudi configuration complete!
2024-06-12 13:31:29 info qudi.core.servers Starting RPyC server "remote-modules-server" on [localhost]:12345
2024-06-12 13:31:29 info qudi.core.servers Starting RPyC server "local-namespace-server" on [localhost]:18861
2024-06-12 13:31:30 info qudi.core.gui.gui Activating main GUI module...
2024-06-12 13:31:34 info qudi.core.gui.main_gui.main_gui.QudiMainGui IPython kernel for qudi main GUI successfully started.
2024-06-12 13:31:34 info qudi.Qudi Initialization complete! Starting Qt event loop...
2024-06-12 13:31:37 info qudi.core.services Client connected to local module service from [127.0.0.1]:56756
2024-06-12 13:31:54 error qudi.util.datafitting Exception while importing qudi.util.fit_models sub-module "qudi.util.fit_models.sine":
Traceback (most recent call last):
  File "C:\Users\emilh\Desktop\Code\Qudi\qudi-env\lib\site-packages\qudi\util\datafitting.py", line 55, in <module>
    inspect.getmembers(importlib.import_module(mod_finder.name), is_fit_model)}
  File "C:\Users\emilh\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\emilh\Desktop\Code\Qudi\qudi-env\lib\site-packages\qudi\util\fit_models\sine.py", line 26, in <module>
    from qudi.util.math import compute_ft
  File "C:\Users\emilh\Desktop\Code\Qudi\qudi-env\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\emilh\Desktop\Code\Qudi\qudi-env\lib\site-packages\qudi\util\math.py", line 35, in <module>
    'hamming': {'func': signal.hamming, 'ampl_norm': 1.0/0.54},
AttributeError: module 'scipy.signal' has no attribute 'hamming'
```

### Additional Comments

The  windows from module scipy.signal has changed to scipy.signal.windows
@
Lib\site-packages\qudi\util\math.py

### Contact Details

emilhenningsen3@gmail.com

**Comment by takuya-ulm** [comment]
Hi @Emillio007 ,

Thank you for creating the issue.
As far as I know, we fixed that issue in the following PR:
https://github.com/Ulm-IQO/qudi-core/pull/91

Could you update your core and try it again?

If you still encounter that issue, please let us know.

**Comment by Neverhorst** [comment]
This has already been fixed since the last `qudi-core` release (v.1.5.0) as @takuya-ulm mentioned. Updating your `qudi-core` installation to the latest version of `main` will fix this.
If you have installed `qudi-core` from the Python package index (PyPI) via `pip`, you have to wait for the next release which should happen within the next few weeks.
